version: '3.8'
services:
  positioning-service:
    build: ./positioning_service
    ports:
      - "8001:8082"
    volumes:
      - ./positioning_service:/app
    restart: unless-stopped

  access-control-service:
    build: ./access_control_service
    ports:
      - "8002:8084"
    volumes:
      - ./access_control_service:/app
    restart: unless-stopped
  
  data-aggregator-service:
    build: ./data_aggregator_service
    ports:
      - "8003:8085"
    volumes:
      - ./data_aggregator_service:/app
      - ./data_aggregator_service//app/data
    restart: unless-stopped
    depends_on:
      - positioning-service
      - access-control-service
  
  alert-service:
    build: ./alert_service
    ports:
      - "8004:8083"
    volumes:
      - ./alert_service:/app
      - ./alert_service//app/data
    restart: unless-stopped
    depends_on:
      - positioning-service
      - access-control-service
      - data-aggregator-service